version: "3"
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  mongo:
    image: mongo:4.0.3-xenial
    ports:
      - "27017:27017"
    volumes:
      - ./.mongodb:/data/db
  worker:
    build:
      context: .
    entrypoint: pipenv run celery
    command: -A tasks worker --loglevel=info
    restart: always
    healthcheck:
      test: celery inspect ping
      interval: 60s
      timeout: 10s
      retries: 3
    environment:
      - API_KEY=SnAB7jQEFs1Ai8XtZdssa14gORT3jWPI7TWdXN97
      - CELERY_BROKER_URL=amqp://rabbitmq:rabbitmq@rabbit:5672
      - CELERY_RESULT_BACKEND=rpc://
      - MONGO_URL=mongodb://mongo:27017
      - C_FORCE_ROOT=true
    depends_on:
      - rabbit
      - mongo
  flower:
    image: mher/flower
    command: ["flower", "--broker=amqp://rabbitmq:rabbitmq@rabbit:5672"]
    ports:
      - 5555:5555
    depends_on:
      - rabbit
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: pipenv run gunicorn app:app -b 0.0.0.0:5000 -w 5 --chdir /usr/src/app/api --log-level debug
    environment:
      - API_KEY=VmVyeSBBd2Vzb21lIEFwbGljYXRpb24gZG9uZSB3aXRoIGhlYXJ0
      - MONGO_URL=mongodb://mongo:27017
    ports:
      - "5000:5000"
    healthcheck:
      test: curl --fail -s http://localhost:5000/health || exit 1
      interval: 60s
      timeout: 10s
      retries: 3
    restart: always
    depends_on:
      - rabbit
      - worker
      - mongo
