apiVersion: v1
kind: Service
metadata:
  name: celery-queue
spec:
  type: LoadBalancer
  selector:
    app: celery
  ports:
    - name: celery-conn
      protocol: TCP
      port: 5672
      targetPort: 5672
