---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  RABBITMQ_USERNAME: "rabbitmq"
  RABBITMQ_PASSWORD: "rabbitmq"
  RABBITMQ_VHOST: "/"
  RABBITMQ_NODE_PORT_NUMBER: "5672"
  RABBITMQ_MANAGER_PORT_NUMBER: "15672"
  WORKER_DEBUG_LEVEL: "info"
  CELERY_BROKER_URL: "amqp://rabbitmq:rabbitmq@rabbit:5672"